# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FK_h8rfM8QUaqVQHnmXahn5hX0pYXZX
"""

#pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# loading the ML model
model=joblib.load("./model_pipeline.pkl")

# loading columns names list
columns_list=joblib.load("./columns_list.pkl")

print(type(columns_list))

print(columns_list)

# loading and printing options for 'cluster'
cluster_options=joblib.load("./cluster_options.pkl")
print(cluster_options)

st.title("Continuous Behavioural Authentication")
st.markdown("To classify user activity using supervised machine learning (binary) classifer which predicts legitimate activity (0) and suspicious activity (1)")

st.header("The following data are recorded when a user is online")

col1,col2=st.columns(2)

with col1:
  avg_key_press_duration=st.number_input("Average Key Press Duration",value=0.0)
  error_rate=st.number_input("Error Rate",value=0.0)
  typing_speed_chars_per_sec=st.number_input("Typing Speed Characters Per Second",value=0.0)
  mouse_avg_speed=st.number_input("Mouse Average Speed",value=0.0)
  click_rate=st.number_input("Click Rate",value=0.0)
  scroll_speed=st.number_input("Scroll Speed",value=0.0)

with col2:
  cluster=st.selectbox("Cluster",options=cluster_options)
  latitude=st.number_input("Latitude",value=0.0)
  longitude=st.number_input("Longitude",value=0.0)
  num_active_apps=st.number_input("Number of active apps",value=0.0)
  foreground_switch_count=st.number_input("Foreground Switch Count",value=0.0)

values=[cluster,avg_key_press_duration,error_rate,typing_speed_chars_per_sec,mouse_avg_speed,click_rate,scroll_speed,latitude,longitude,num_active_apps,foreground_switch_count]
input_df=pd.DataFrame([dict(zip(columns_list,values))])
# Display input
print(input_df)
print("Input columns:", input_df.columns.tolist())

st.write("Input Dataframe:")
st.write(input_df)

if st.button("Predict",type="primary"):
  prediction=model.predict(input_df)
  st.write("Predicted score:",prediction)
  if(prediction==0):
    st.write("Legitimate Activity")
  else:
    st.write("Suspicious Activity")